# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import addressbook_pb2 as addressbook__pb2


class EmailInfoStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetEmailInfo = channel.unary_unary(
        '/EmailInfo/GetEmailInfo',
        request_serializer=addressbook__pb2.Person.SerializeToString,
        response_deserializer=addressbook__pb2.Emailaddress.FromString,
        )


class EmailInfoServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetEmailInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EmailInfoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetEmailInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetEmailInfo,
          request_deserializer=addressbook__pb2.Person.FromString,
          response_serializer=addressbook__pb2.Emailaddress.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'EmailInfo', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
