# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addressbook.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='addressbook.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11\x61\x64\x64ressbook.proto\"-\n\x06Person\x12\x11\n\tFirstName\x18\x01 \x01(\t\x12\x10\n\x08LastName\x18\x02 \x01(\t\"\x1d\n\x0c\x45mailaddress\x12\r\n\x05\x45mail\x18\x01 \x01(\t25\n\tEmailInfo\x12(\n\x0cGetEmailInfo\x12\x07.Person\x1a\r.Emailaddress\"\x00\x62\x06proto3')
)




_PERSON = _descriptor.Descriptor(
  name='Person',
  full_name='Person',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='FirstName', full_name='Person.FirstName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='LastName', full_name='Person.LastName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=66,
)


_EMAILADDRESS = _descriptor.Descriptor(
  name='Emailaddress',
  full_name='Emailaddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Email', full_name='Emailaddress.Email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=97,
)

DESCRIPTOR.message_types_by_name['Person'] = _PERSON
DESCRIPTOR.message_types_by_name['Emailaddress'] = _EMAILADDRESS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), dict(
  DESCRIPTOR = _PERSON,
  __module__ = 'addressbook_pb2'
  # @@protoc_insertion_point(class_scope:Person)
  ))
_sym_db.RegisterMessage(Person)

Emailaddress = _reflection.GeneratedProtocolMessageType('Emailaddress', (_message.Message,), dict(
  DESCRIPTOR = _EMAILADDRESS,
  __module__ = 'addressbook_pb2'
  # @@protoc_insertion_point(class_scope:Emailaddress)
  ))
_sym_db.RegisterMessage(Emailaddress)



_EMAILINFO = _descriptor.ServiceDescriptor(
  name='EmailInfo',
  full_name='EmailInfo',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=99,
  serialized_end=152,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetEmailInfo',
    full_name='EmailInfo.GetEmailInfo',
    index=0,
    containing_service=None,
    input_type=_PERSON,
    output_type=_EMAILADDRESS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EMAILINFO)

DESCRIPTOR.services_by_name['EmailInfo'] = _EMAILINFO

# @@protoc_insertion_point(module_scope)
